# Generated by Django 3.1.6 on 2021-06-16 14:46

from django.db import migrations
from taxonomy.models import Topic


def forwards(apps, schema_editor):
    topics = [
        'Retail',
        'CIO',
        'Education',
        'Supply Chain',
        'Restaurant',
        'Grocery',
        'BioPharma',
        'HR',
    ]
    for topic in topics:
        internal_name = topic.lower().replace(' ', '_')
        existing = Topic.objects.filter(internal_name=internal_name)
        if not existing.exists():
            topic = Topic(display_name=topic, internal_name=internal_name)
            topic.save()


def backwards(apps, schema_editor):
    Topic.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
