# Generated by Django 3.1.6 on 2021-06-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_manual_set_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiveSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('url_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
