# Generated by Django 3.1.6 on 2021-06-16 15:22

from django.db import migrations
from taxonomy.models import DiveSite


def forwards(apps, schema_editor):
    sites = [
        'Retail',
        'CIO',
        'Education',
        'Supply Chain',
        'Restaurant',
        'Grocery',
        'BioPharma',
        'HR',
    ]
    for site in sites:
        url_name = '{}dive'.format(site.lower().replace(' ', ''))
        existing = DiveSite.objects.filter(url_name=url_name)
        if not existing.exists():
            divesite = DiveSite(display_name='{} Dive'.format(site), url_name=url_name)
            divesite.save()


def backwards(apps, schema_editor):
    DiveSite.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_divesite'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
