# Generated by Django 3.1.6 on 2021-06-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_manual_set_topics'),
        ('wavepool', '0002_alter_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='topics',
            field=models.ManyToManyField(to='taxonomy.Topic'),
        ),
    ]
