# Generated by Django 3.1.6 on 2021-06-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_manual_set_divesites'),
        ('wavepool', '0003_newspost_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='divesite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.divesite'),
        ),
    ]
